temp/objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Photo__c</fullName>
        <label>Photo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/FileUploaderController.cls
public class FileUploaderController {
    
    public ContentVersion conVer {get; set;}
    public ContentDocumentLink conDocLink {get; set;}
    public Candidate__c thisCandidate{get; set;}
   
    public FileUploaderController(ApexPages.StandardController controller){
        thisCandidate = (Candidate__c)controller.getRecord();
        conVer = new ContentVersion();
    }

    public PageReference uploadFile() {
        List<ContentVersion> conVerList = new List<ContentVersion>();
        List<ContentDocumentLink> conDocLinkList = new List<ContentDocumentLink>();
        
        if (conVer.VersionData == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, Label.Error_No_File));
            conVer.VersionData = null;
            return null;
        }
        
        /***  Блок для проверки расширения  ***/
        String path = conVer.PathOnClient;
        Set<String> acceptedExtensions = new Set<String> {'.jpeg', '.jpg', '.png', '.tiff', '.tif', '.bmp', '.jpe', '.jfif'};
        Boolean found = false;
      
        for(String ext : acceptedExtensions){
            if(found = path.endsWith(ext)){
                break;
            }   
        }
        if(!found){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, Label.Error_Extension));
            conVer.VersionData = null;
            return null; 
        }
        /***  Конец блока  ***/
                
        conVerList.add(conVer);
        try {
            insert conVerList;              
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, e.getMessage()));
        }
        
        thisCandidate.Photo__c = conVer.Id;
        update thisCandidate;
        
        if (conVer.ContentDocumentId == null) {
            
            Id conDoc = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =: conVer.Id].ContentDocumentId;
            
            conDocLink = new ContentDocumentLink(
                LinkedEntityId = thisCandidate.Id,
                ContentDocumentId = conDoc,
                ShareType = 'I'
            );
            
            conDocLinkList.add(conDocLink);
            try {
            	insert conDocLinkList;
        	} catch(Exception e) {
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, e.getMessage()));
        	}
        } 
        conVer.VersionData = null;
        return null;
    }

    public PageReference deleteFile() {
        
        thisCandidate.Photo__c = null;
        
        try {
            update thisCandidate;
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.SEVERITY.ERROR, e.getMessage()));
        }
        conVer = new ContentVersion();
        return null;
    }
}