temp/objects/Position__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Not Approved</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Post_Status__c</fullName>
        <label>Post Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Posted</fullName>
                </value>
                <value>
                    <fullName>Not posted</fullName>
                    <default>true</default>
                    <label>Not posted</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

temp/classes/PositionButtonsController.cls
public class PositionButtonsController {
    
    public static Position__c position = [SELECT Id, Post_Status__c, Approval_Status__c, Status__c
                                   FROM Position__c
                                   WHERE Id =: ApexPages.CurrentPage().getparameters().get('Id')];
    public static String positionStatus{get;set;}
    public static String successResultMessage{get;set;}
    public static String errorResultMessage{get;set;}
    
    public PositionButtonsController(ApexPages.StandardController controller){
        positionStatus = position.Post_Status__c;
    }
    
    public static void postJobAdvertisement(){
        try{
            HttpResponse response = CalloutJobAdvertisement.postCalloutResponseContents(position.Id);
            position.Post_Status__c = 'Posted';
            update position;
            successResultMessage = System.Label.Post_JobAdv_Success_Result_Message;
        } catch(Exception e){
            errorResultMessage = e.getMessage();
            if(e.getMessage() == System.Label.Item_already_exists){
                position.Post_Status__c = 'Posted';
            	update position;
            }
        }
        positionStatus = position.Post_Status__c;
    }
    
    public static void deleteJobAdvertisement(){
        try{
            HttpResponse response = CalloutJobAdvertisement.deleteCalloutResponseContents(position.Id);
            position.Post_Status__c = 'Not posted';
            update position;
            successResultMessage = System.Label.Delete_JobAdv_Success_Result_Message;
        } catch(Exception e){
            errorResultMessage = e.getMessage();
            if(e.getMessage() == System.Label.Item_does_not_exists){
                position.Post_Status__c = 'Not posted';
            	update position;
            }
        }
        positionStatus = position.Post_Status__c;
    }
    
    public static void updateJobAdvertisement(){
        try{
            HttpResponse response = CalloutJobAdvertisement.putCalloutResponseContents(position.Id);
            successResultMessage = System.Label.Update_JobAdv_Success_Result_Message;
        } catch(Exception e){
            errorResultMessage = e.getMessage();
            if(e.getMessage() == System.Label.Item_does_not_exists){
                position.Post_Status__c = 'Not posted';
            	update position;
            }
        }
        positionStatus = position.Post_Status__c;
    }
}